export const firstNames = [
    "James", "John", "Robert", "Michael", "William", "David", "Richard", "Charles", "Joseph", "Thomas",
    "Mary", "Patricia", "Jennifer", "Linda", "Elizabeth", "Barbara", "Susan", "Jessica", "Sarah", "Karen",
    "Christopher", "Daniel", "Paul", "Mark", "Donald", "George", "Kenneth", "Steven", "Edward", "Brian",
    "Nancy", "Lisa", "Betty", "Margaret", "Sandra", "Ashley", "Kimberly", "Emily", "Donna", "Michelle",
    "Ronald", "Timothy", "Jason", "Jeffrey", "Ryan", "Jacob", "Gary", "Nicholas", "Eric", "Jonathan",
    "Stephen", "Larry", "Justin", "Scott", "Brandon", "Benjamin", "Samuel", "Gregory", "Frank", "Alexander",
    "Raymond", "Patrick", "Jack", "Dennis", "Jerry", "Tyler", "Aaron", "Jose", "Adam", "Nathan",
    "Henry", "Douglas", "Zachary", "Peter", "Kyle", "Walter", "Ethan", "Jeremy", "Harold", "Keith",
    "Christian", "Roger", "Noah", "Gerald", "Carl", "Terry", "Sean", "Austin", "Arthur", "Lawrence",
    "Jesse", "Dylan", "Bryan", "Joe", "Jordan", "Billy", "Bruce", "Albert", "Willie", "Gabriel",
    "Logan", "Alan", "Juan", "Wayne", "Roy", "Ralph", "Randy", "Eugene", "Vincent", "Russell",
    "Elijah", "Louis", "Bobby", "Philip", "Johnny", "Bradley", "Martin", "Howard", "Matthew", "Anthony",
    "Carol", "Amanda", "Melissa", "Deborah", "Stephanie", "Rebecca", "Sharon", "Laura", "Cynthia", "Kathleen",
    "Amy", "Shirley", "Angela", "Helen", "Anna", "Brenda", "Pamela", "Nicole", "Emma", "Samantha",
    "Katherine", "Christine", "Debra", "Rachel", "Catherine", "Carolyn", "Janet", "Ruth", "Maria", "Heather",
    "Diane", "Virginia", "Julie", "Joyce", "Victoria", "Olivia", "Kelly", "Christina", "Lauren", "Joan",
    "Evelyn", "Judith", "Megan", "Cheryl", "Andrea", "Hannah", "Martha", "Jacqueline", "Frances", "Gloria",
    "Ann", "Teresa", "Kathryn", "Sara", "Janice", "Jean", "Alice", "Madison", "Doris", "Abigail",
    "Julia", "Judy", "Grace", "Denise", "Amber", "Marilyn", "Beverly", "Danielle", "Theresa", "Sophia",
    "Marie", "Diana", "Brittany", "Natalie", "Isabella", "Charlotte", "Rose", "Alexis", "Kayla", "Lori",
    "Isaac", "Oliver", "Owen", "Caleb", "Mason", "Luke", "Jackson", "Levi", "Wyatt", "Hunter",
    "Christian", "Isaiah", "Landon", "Gavin", "Connor", "Charles", "Eli", "Ezra", "Aaron", "Nathan",
    "Thomas", "Cameron", "Mila", "Aria", "Chloe", "Lily", "Eleanor", "Riley", "Zoey", "Nora",
    "Lily", "Stella", "Hazel", "Aurora", "Naomi", "Elena", "Lucy", "Emilia", "Everly", "Luna"
];

export const lastNames = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez",
    "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin",
    "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson",
    "Walker", "Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores",
    "Green", "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell", "Carter", "Roberts",
    "Gomez", "Phillips", "Evans", "Turner", "Diaz", "Parker", "Cruz", "Edwards", "Collins", "Reyes",
    "Stewart", "Morris", "Morales", "Murphy", "Cook", "Rogers", "Gutierrez", "Ortiz", "Morgan", "Cooper",
    "Peterson", "Bailey", "Reed", "Kelly", "Howard", "Ramos", "Kim", "Cox", "Ward", "Richardson",
    "Watson", "Brooks", "Chavez", "Wood", "James", "Bennett", "Gray", "Mendoza", "Ruiz", "Hughes",
    "Price", "Alvarez", "Castillo", "Sanders", "Patel", "Myers", "Long", "Ross", "Foster", "Jimenez",
    "Powell", "Jenkins", "Perry", "Russell", "Sullivan", "Bell", "Coleman", "Butler", "Henderson", "Barnes",
    "Gonzales", "Fisher", "Vasquez", "Simmons", "Romero", "Jordan", "Patterson", "Alexander", "Hamilton", "Graham",
    "Reynolds", "Griffin", "Wallace", "Moreno", "West", "Cole", "Hayes", "Woods", "Oritz", "Bryant",
    "Herrera", "Washington", "Mcdonald", "Dixon", "Gibson", "Ford", "Silva", "Stone", "Harrison", "Richards",
    "Cruz", "Oliver", "Pierce", "Kennedy", "Tucker", "Guzman", "Hoffman", "Fletcher", "Byrd", "Hunt",
    "Palmer", "Shaw", "Holmes", "Robertson", "Boyd", "Mason", "Hicks", "Knight", "Fox", "Wagner",
    "Warren", "Obrien", "Meyer", "Rice", "Dunn", "Daniels", "Weaver", "Webb", "Valdez", "Glover",
    "Harper", "Walsh", "Sims", "Garrison", "Fleming", "Bates", "Hale", "Gregory", "Pena", "Nunez",
    "Riley", "Arnold", "Moran", "Barber", "Todd", "Mann", "Blake", "Erickson", "Wolfe", "Strickland",
    "Love", "Thornton", "Parsons", "Benson", "Vargas", "Maxwell", "Steele", "Higgins", "Doyle", "Vega",
    "Walton", "Mccoy", "Townsend", "Goodman", "Rowe", "Bowman", "Bowers", "Casey", "Cross", "Norton"
];
